package vars

var (
	FORWARDER_LOG        = "FORWARDER_LOG"
	FORWARDER_CLIENT_LOG = "FORWARDER_CLIENT_LOG"
	LISTENER_CLIENT_LOG  = "LISTENER_CLIENT_LOG"
	FORWARDER_COMMAND    = "FORWARDER_COMMAND"
	LISTENER_COMMAND     = "LISTENER_COMMAND"
)

var (
	DEBUG     = 7
	INFO      = 6
	NOTICE    = 5
	WARNING   = 4
	ERROR     = 3
	CRITICAL  = 2
	ALERT     = 1
	EMERGENCY = 0
)
